apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hybrid-deployment-pipeline
spec:
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "https://github.com/myorg/hybrid-cloud-app.git"
    - name: build-image
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: "quay.io/myorg/hybrid-cloud-app:latest"
    - name: deploy
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: "oc apply -f deployment.yaml"
